apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap-logstash-pipeline-botdefense.yaml
- configmap-logstash-pipeline-waf.yaml
- deploy-elk.yaml
- deploy-grafana.yaml
- svc-elk-clusterip.yaml
- svc-elk-lb.yaml
- svc-grafana-lb.yaml
namespace: monitoring